### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/project#48]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] project_category
- [ ] project_closure_restrictions
- [ ] project_description
- [ ] project_duplicate_analytic_hierarchy
- [ ] project_duplicate_fix
- [ ] project_issue_closure_restrictions
- [ ] project_issue_create_task_defaults
- [ ] project_issue_fix
- [ ] project_issue_order
- [ ] project_issue_product
- [ ] project_issue_solutions
- [ ] project_issue_solutions_product
- [ ] project_kanban_open_project
- [ ] project_related_projects
- [ ] project_stage
- [ ] project_tags
- [ ] project_task_activity
- [ ] project_task_delegate
- [ ] project_task_issues
- [ ] project_task_order
- [ ] project_task_phase
- [ ] project_task_portal_unfollow
- [ ] project_usability
- [ ] project_usability_issue
